### ISSUE TITLE
Single right click won't work

### ISSUE THREAD

**Issue by jreybert** [jimporter/gesticulate#1]
When gesticulate is enabled, I can't right click on a web page for contextual menu.
When it is disabled, right click makes the contextual menu appear.

I could try with a fresh firefox profile and gesticulate addon installed only if you need.

**Comment by jimporter** [comment]
Which OS? Gesticulate changes context menu behavior on Linux and OS X so that the context menu appears on mouseup, not mousedown.

**Comment by jreybert** [comment]
This is with Linux (more precisely centos7.2).

**Comment by jimporter** [comment]
Works fine for me on Mint 17, Firefox 46.0, and the latest nightly of Gesticulate. What version of Gesticulate are you using?

**Comment by jreybert** [comment]
My bug context is really poor, and miss the essential:
I am running firefox 48. It has already broke things around tabs and mouse wheel, I suspect them to change a lot of stuff around mouse UI.

Gesticualte version is 0.1.1

**Comment by jimporter** [comment]
I did change some of the mouse state handling since 0.1.1, so that could be it. There was a bug where I hit a race condition during page unloads and the mouse state got out of sync.

Could you try with the latest master revision? If you download the repo and run `make package`, you should get an (unsigned) .xpi file that you can drag and drop onto Firefox to test it out. If it works, I'll fix the last couple things I need to do and then release 0.2. Thanks!

**Comment by jreybert** [comment]
Well I tried 0.2pre, and this is worse:
- on normal webpage, right clic, and even rock gestures does not work
- on about:addons page (which seems special), both right clic and rock gestures work like a charm.

**Comment by jimporter** [comment]
Apparently I can't create content events from a chrome context with the e10s shim. They also swapped the order of the mousedown and contextmenu events. The latter is easy to fix; the former is not.

In the meantime, I'd recommend not using an e10s-enabled build or doing all your gestures on the chrome parts of Firefox (i.e. anything that's not web content).

**Comment by jimporter** [comment]
Right-clicking in a webpage should work as of edc43a9ab725c8bb1f5d04db9b1734d69d0ba1a3. You can also disable the "delay context menu" behavior with the hidden pref `extensions.gesticulate.delay_context_menu`.

**Comment by jimporter** [comment]
I've created an alpha version of this add-on as a Web Extension, available [here](https://addons.mozilla.org/en-US/firefox/addon/gesticulate/versions/beta?page=1#version-0.3a1). It's currently pretty busted, but it's a start...

**Comment by jimporter** [comment]
Ok, something apparently got fixed in Firefox so now rocker gestures work correctly in a normal webpage even under e10s. However, single right clicks still don't work (except on Windows, which behaves differently). I'm trying to fix that, but I'm really not sure how to do it yet...

If you want to follow along, you can check out the [e10s](https://github.com/jimporter/gesticulate/tree/e10s) branch.

**Comment by jimporter** [comment]
@jreybert I'm not sure if you're still following along with this, but I've uploaded an alpha version with this fixed to AMO: <https://addons.mozilla.org/en-US/firefox/addon/gesticulate/versions/0.3a2>. There are still a couple issues keeping me from releasing it for real, but the basics should all work. Let me know if you have any further issues, and sorry for taking so long to resolve this!

**Comment by jreybert** [comment]
Hi @jimporter . I must admit that I finally reverted back to mouse gesture addon. I'll give gesticulate a try, especially if you think to be compatible witht he new firefox API.

**Comment by jimporter** [comment]
The goal is to be compatible with WebExtensions one day, but that's going to require me to write some new WebExtension APIs (and get them accepted into Firefox). Right now, the alpha *is* e10s-compatible though, which at least is a start.

**Comment by jimporter** [comment]
Note that this add-on is now fully-compatible with Firefox 57+ (although Mac and Linux users will probably want 58+).

**Comment by jreybert** [comment]
It works like a charm!
