### ISSUE TITLE
Gestures don't work on Ubuntu

### ISSUE THREAD

**Issue by fishdavidson** [jimporter/gesticulate#2]
I'm currently running Ubuntu 17.04 with FF57 and the rocker gestures do not appear to work. I haven't tried using the source to make it (only tried installing the addon from AMO), but I've tried using all four gestures listed and none of them work. I've tried restarting the browser after installing/uninstalling and going to different pages, but nothing seems to work. A few google searches seem to indicate that this issue may be affecting Linux and Mac users of similar plugins, but I don't have the coding skills to say for certain. Please let me know if there's anything I can do to help test this plugin, because I really miss having rocker gestures!

**Comment by jimporter** [comment]
LMB->RMB works fine for me on Linux. However, anything initiated with right-click won't work normally; additionally, touchpads' middle mouse button generally doesn't work as a gesture initiator because of how the drivers treat holding it down (it basically activates scroll-wheel mode).

To perform gestures starting with RMB, you have to *double* right click, since the first time you mousedown with the RMB, it opens the context menu. This is a bug (more-or-less) in Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1360278

It's probably possible to fix this with some code changes, but given that the add-on doesn't even work 100% on Windows yet (sometimes context menus are incorrectly suppressed), I haven't prioritized it.

Also note that gestures don't work on about: pages or addons.mozilla.org due to security restrictions.

**Comment by jimporter** [comment]
On Firefox 58, this should work once you toggle `ui.context_menus.after_mouseup` to true in `about:config`.
